# Generated by Django 4.0 on 2021-12-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InteractionAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='info',
        ),
    ]
